add_newline = false

format = """
$hostname$directory$git_branch$git_commit$git_status$nodejs$golang$ruby
[❯](blue) """

[hostname]
ssh_only = true
format = "on [$hostname](bold red)/"
trim_at = ".companyname.com"
disabled = false

[directory]
style = "fg:black"
truncation_length = 8
truncation_symbol = "…"
format = "[$path]($style) "

[nodejs]
style = "fg:green"
symbol = "ⓝ"
format = "[$symbol $version]($style) "

[golang]
style = "fg:45"
symbol = "ⓖ"
format = "[$symbol $version]($style) "

[ruby]
style = "fg:red"
symbol = "ⓡ"
format = "[$symbol $version]($style) "
